require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*'

Metrics/LineLength:
  Exclude:
    - 'Rakefile'
    - 'config/environments/production.rb'
    - 'config/environments/development.rb'
    - 'config/environments/test.rb'
    - 'config/application.rb'
    - 'config/puma.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'config/initializers/content_security_policy.rb'
    - 'db/seeds.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'